### ISSUE TITLE
How to show the mongodate to view

### ISSUE THREAD

**Issue by mohdbashir** [mohorev/yii2-mongodate-behavior#1]
I have added the MongoDateBehavior and my date is saved as type of mongo date  and now the problem is how to convert it show on page.

``` php
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
             'created_at:datetime',            
            ['class' => 'yii\grid\ActionColumn'],
        ],
]); ?>
```

datetime not converting the mongo date and showing error.

**Comment by mohorev** [comment]
Use like this:

``` php
<?= GridView::widget([
    'dataProvider' => $model->search(),
    'filterModel' => $model,
    'columns' => [
        [
            'attribute' => 'created_at',
            'format' => ['date', 'medium'],
            'options' => ['class' => 'col-lg-1'],
            'value' => function ($model) {
                return $model->created_at->sec;
            },
        ],
        // or
        'created_at.sec:datetime',
        [
            'class' => ActionColumn::className(),
        ],
    ],
]); ?>

```

**Comment by mohdbashir** [comment]
Yes it is working. 

But it is not working for DetailView widget and showing error: "Object of class Closure could not be converted to string"

<?= DetailView::widget([
        'model' => $model[0],
        'attributes' => [           
            [
            'attribute' => 'expires_on',
            'format' => ['date', 'medium'],            
            'value' => function ($model) {
                return $model[0]['expires_on']->sec
                },
            ],
            'source',
            'status',
           // 'created_at:datetime',
            //'updated_at:datetime'
        ],
    ]) ?>

**Comment by mohdbashir** [comment]
Yes it is working.
